### ISSUE TITLE
Images load late

### ISSUE THREAD

**Issue by johjacb** [aFarkas/lazyflickity#1]
Thanks for your work on this! Images that I have as part of the carousel load so late in the stack of assets. Is there any way to not lazyload the first image in the carousel, or to load the images earlier?

![screen shot](https://cloud.githubusercontent.com/assets/2394337/11221700/2062f17c-8d2c-11e5-9b08-770e217e0d38.png)

**Comment by aFarkas** [comment]
lazyloading always means, that JS and CSS has to be loaded. So you are always deferring image loads with this.

The crucial image(s) should be loaded normally without lazyload class and with `src`/`srcset` instead of `data-src`/`data-srcset`.

**Comment by johjacb** [comment]
thanks for your reply. I'm guessing the delayed load is the same reason for this issue: https://github.com/aFarkas/lazysizes/issues/185

I've got a cms feeding the carousel, so unfortunately, I can't tweak just the first image from the set.

**Comment by aFarkas** [comment]
@johjacb 
Ok, I understand your problem. This is why I have written this:
https://github.com/aFarkas/lazysizes#tip-wherehow-to-include-lazysizes

Looking into your waterfall the only thing I could advise is to add flickity to the bottom of the page. However flickity itself has also heavy influence on the UI (unless your are very aware of this and pre-define the CSS of flickity so that your initial state looks the same without flickity active.)

Are you loading boots.css with `loadCSS` or are you using `<link rel="prefetch preload" ...>`?

As already said lazyloading always delays things and if you don't want this, you need to change this. 

Another way is to delay other things, that stand in your way. Which often can be done with more complex websites with a lot of assets. But this isn't the problem in your case.

I hope you are aware of the fact that lazysizes starts to load those images at the same time as `load.gif` is started. Don't know why the waterfall is so off here. Maybe you should remove the browser-sync script to test this.

**Comment by johjacb** [comment]
I did read that section (many times!) - I've tried multiple different locations/strategies to get lazyflickity initialized as soon as possible. I am putting the critical flickity styles inline in the head. boots.css is being loaded using Google's loader JS. I've also done extensive testing with a staging server for the live site, not local with browser-sync and see the same results. 

I was just checking in to see if I had done something blatantly wrong :)

**Comment by aFarkas** [comment]
In general, I'm very interested to see this in action and to fiddle around, but I must say that in general this problem can only be solved the correct way on the backend site, by injecting the position information into the image rendering template. 

If you want to mail me your site, I would be happy.

**Comment by johjacb** [comment]
well i figured out the issue but I haven't had time to do a full debrief as to why. 

The inline css from the lazyflickity demo that I had in the <head> was the culprit.

```
    <style>
        /* hide cells until fickity is ready -> so lazySizes doesn't load until layout is done */
        .gallery-cell {
            width: 100%;
            visibility: hidden;
        }
        .flickity-slider > .gallery-cell {
            visibility: visible;
        }
        .ratio-box {
            position: relative;
            height: 0;
            display: block;
            width: 100%;
            /* padding-bottom is calculated and rendered in to HTML */
        }
        .ratio-box > * {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            display: block;
        }
    </style>
```

probably a collision with some of my other styles. thanks for looking in to this!

**Comment by aFarkas** [comment]
Thanks, I have changed my example to use the following CSS:

``` css
.gallery-cell:first-child,
.flickity-slider > .gallery-cell {
    visibility: visible;
}
```

This way the first element will be loaded. If you want to hide it, you can use `opacity: 0.01;`.
